// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer DIRECT_DATABASE_URL for migrations when available.
    // - Helps with Supabase pooler differences (transaction pooler vs direct/session).
    // - Runtime Prisma usage still comes from app env (src/lib/db.ts) via DATABASE_URL.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
